### ISSUE TITLE
<custom tags>

### ISSUE THREAD

**Issue by yestoall** [mattdonnelly/MDHTMLLabel#6]
thanks for the <font> update, it's works really good.

i'm thinking now in the idea of create <custom tags>, with user defined attributes.

i'm playing with your code and it seems to be easy to implement it.
you write a good code objectiveC code.
i'm not an objectiveC developer, i'm feel more confortable in ruby (rubymotion)

thanks again for share your code, it's great.

**Comment by mattdonnelly** [comment]
Sorry for the delay in getting back you on this. I've been thinking about it on and off as I've been working on updates and after a lot of jumping back and forth between decisions I've finally made a decision.

Unfortunately, I've decided that isn't something I'm going to implement, as I think it goes against the purpose of the project. The intention is that any styling of text should be done using HTML rather than code. For this reason, I think allowing users to specify custom tags and how they should be styled doesn't make sense as it would be, in a way, extending the functionality of HTML which is not something I want to do.

It's possible I'll revise this opinion in the future, but at the moment this is what I feel makes the most sense for the purpose of this project. Thank you for taking and interest though and I really appreciate the feedback!
